### Linear Algebra - Matrix operations
Use NumPy to perform the following tasks:

In [0]:
from sklearn.decomposition import non_negative_factorization
import numpy as np

**Question 1.** Compute the multiplication of the following matrices:

[[1, 0], [0, 1]]

[[1, 2], [3, 4]]

In [0]:
p = [[1, 0], [0, 1]]
q = [[1, 2], [3, 4]]
print("matrix:")
print(p)
print(q)
result = np.dot(p, q)
print("Result_matrix multiplication:")
print(result)

matrix:
[[1, 0], [0, 1]]
[[1, 2], [3, 4]]
Result_matrix multiplication:
[[1 2]
 [3 4]]

**Question 2.** Generate an array of length 3n filled with the cyclic pattern 1, 2, 3.

In [0]:
def cyclic(n):
  a = np.array([1,2,3])
  b = np.resize(a, 3*n)
  print(b)

cyclic(4) #for example, I'll put n=4

[1 2 3 1 2 3 1 2 3 1 2 3]

**Question 3.** Create a 10×10 matrix of zeros and then "frame" it with a border of ones.

In [0]:
x = np.zeros((10,10))
print (x)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]

In [0]:
# Put '1' in first & last columns
x[:10, ::9] = 1  # Put 1 in all 10 rows by every other 9 column (first&last column)
x[::9, :10] = 1  # Put 1 in first&last row in every row
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

**Question 4.** Create a random 3×5 array using the np.random.rand(3, 5) function and compute: the sum of all the entries, the sum of the rows and the sum of the columns. (many Numpy functions have an optional axis= argument!)

In [0]:
A = np.random.rand(3, 5)
A

Out[108]: array([[0.45536684, 0.89381634, 0.45746122, 0.88600159, 0.5674958 ],
 [0.86163159, 0.23779538, 0.15184267, 0.59557825, 0.11331781],
 [0.21366931, 0.28207171, 0.52281193, 0.50435282, 0.85003732]])

In [0]:
# 1) Sum of all the entries
print(np.sum(A))

7.59325057603738

In [0]:
# 2) Sum of the rows 
print(np.sum(A, axis=1))

[3.26014179 1.96016571 2.37294308]

In [0]:
# 3) Sum of the columns
print(np.sum(A, axis=0))

[1.53066774 1.41368342 1.13211582 1.98593266 1.53085093]

**Question 5.** Given the following arrays representing logical values (0 = False, 1 = True) compute the logical AND and logical OR operations for every pair of values of the two arrays: [1, 1, 0, 0] [1, 0, 1, 0] Hint: you may need to set the data type (dtype) of the array's elements to 'bool'

In [0]:
A = np.array([1, 1, 0, 0], dtype=bool)
B = np.array([1, 0, 1, 0], dtype=bool)

In [0]:
A & B  # logical AND

Out[113]: array([ True, False, False, False])

In [0]:
A | B # logical OR

Out[114]: array([ True, True, True, False])

**Question 6.** Find indices of non-zero elements from [1, 2, 0, 0, 4, 0]

In [0]:
print (np.nonzero([1, 2, 0, 0, 4, 0]))

(array([0, 1, 4]),)

**Question 7.** Create a 8×8 array with random values and find minimum and maximum value

In [0]:
X = np.random.random((8,8))
print(X) 

[[0.83766811 0.00879627 0.3893411 0.85412363 0.23251799 0.07479461
 0.94505746 0.2170855 ]
 [0.96337328 0.02192131 0.45726549 0.56581686 0.37523245 0.88193136
 0.89271631 0.61286089]
 [0.96995386 0.01715775 0.07118567 0.69816632 0.78671072 0.92927636
 0.90242806 0.70478519]
 [0.93051912 0.93437684 0.27624524 0.69442864 0.78062824 0.62946869
 0.05122183 0.46742207]
 [0.70719175 0.27406574 0.16730789 0.27138242 0.70686747 0.83370982
 0.74051115 0.6579723 ]
 [0.76237345 0.88633627 0.58851977 0.54164183 0.90998508 0.93158475
 0.25033659 0.9376888 ]
 [0.03511097 0.25076911 0.97021436 0.31804271 0.60757819 0.14965165
 0.07315816 0.01852102]
 [0.22105262 0.46771684 0.72572955 0.14021542 0.18819908 0.57392751
 0.27059407 0.35899159]]

In [0]:
Min, Max = X.min(), X.max()
print(Min, Max) # min and Max values of random 8x8 array

0.008796265552513227 0.9702143558937557

**Question 8.** Create a 8×8 array with random natural values from the range (1-100) on the diagonal, other values should be 0. Hint: You can use numpy's 'eye' function.

In [0]:
C = np.random.randint(1, 101, size=(8,8))

In [0]:
np.eye(8) * np.diag(C)

Out[119]: array([[ 67., 0., 0., 0., 0., 0., 0., 0.],
 [ 0., 6., 0., 0., 0., 0., 0., 0.],
 [ 0., 0., 38., 0., 0., 0., 0., 0.],
 [ 0., 0., 0., 100., 0., 0., 0., 0.],
 [ 0., 0., 0., 0., 59., 0., 0., 0.],
 [ 0., 0., 0., 0., 0., 48., 0., 0.],
 [ 0., 0., 0., 0., 0., 0., 71., 0.],
 [ 0., 0., 0., 0., 0., 0., 0., 23.]])

**Question 9.** Write a function which creates an n×n matrix with (i,j)-entry equal to i+j.

In [0]:
# Method 1 - Use 'fromfunction'
# (*caution: in NumPy, row index(i) and column index(j) start from '0' not '1')
n=3   # the below result is when 'n=3' (of course, 'n' can be any positive integer)
np.fromfunction(lambda i, j: i+j, (n,n))

Out[122]: array([[0., 1., 2.],
 [1., 2., 3.],
 [2., 3., 4.]])

In [0]:
# Method 2 - Create empty nxn array and fill it using 'for' loop
n=3 
X = np.empty(shape=(n,n), dtype=int)

for i in range(n):
  for j in range(n):
    X[i,j] = i+j
    
X

Out[123]: array([[0, 1, 2],
 [1, 2, 3],
 [2, 3, 4]])

**Question 10.** Write a function which creates an n×n matrix with rows having subsequent values multiplied by the row's number. For example for n = 4:

[[0, 1, 2, 3], [0, 2, 4, 6], [0, 3, 6, 9], [0, 4, 8, 12]]

In [0]:
n=4 #the result below is the result of the function when n=4
np.fromfunction(lambda i, j: [i-i,j]*(i+1), (n,n)) 

Out[124]: array([[[ 0., 0., 0., 0.],
 [ 0., 0., 0., 0.],
 [ 0., 0., 0., 0.],
 [ 0., 0., 0., 0.]],

 [[ 0., 1., 2., 3.],
 [ 0., 2., 4., 6.],
 [ 0., 3., 6., 9.],
 [ 0., 4., 8., 12.]]])